name: BayRock Studios
favicon: null
layout_spectrum: 0.3991179228760302
typography_spectrum: 0.9685516422614455
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.45530897402204573
  lightness: 0.09498748020268977
  saturation: 0.8054440764244646
  rhythmicContrast: 0.7435410742182285
purpose: []
